name: CI

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  install-deps:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Install latest npm
        run: npm install -g npm@latest
      - name: Install
        run: npm ci --prefer-offline

  build-test-1:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: install-deps
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm run build
      - uses: amondnet/vercel-action@f445edf99fe899f0797463ca6b010746ce4e910e
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_1_ID }}

  build-test-2:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: install-deps
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm run build
      - uses: amondnet/vercel-action@f445edf99fe899f0797463ca6b010746ce4e910e
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_2_ID }}
